# Generated by Django 5.2.4 on 2025-08-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('piso', 'Piso'), ('local', 'Local'), ('garaje', 'Garaje'), ('trastero', 'Trastero')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('planta', models.CharField(blank=True, max_length=10)),
                ('puerta', models.CharField(blank=True, max_length=10)),
                ('metros', models.FloatField()),
                ('habitaciones', models.IntegerField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='inmuebles.propietario')),
            ],
        ),
    ]
