# Generated by Django 5.2.4 on 2025-08-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquilinos', to='portada.inmueble'),
        ),
    ]
