# Generated by Django 5.2.4 on 2025-08-18 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0002_inquilino_inmueble'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipospago_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipospago_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='quien_por_defecto',
            field=models.CharField(blank=True, choices=[('inquilino', 'Inquilino'), ('propietario', 'Propietario')], max_length=20),
        ),
    ]
