# Generated by Django 5.2.4 on 2025-08-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0003_tipopago_activo_tipopago_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
